[project]
name = "uv-hydra-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clearml>=2.1.3",
    "hydra-core>=1.3.2",
]
